spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wt_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: wt19960825
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
server:
  port: 8082